<?php

namespace TFT\personneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * jeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jeuRepository extends EntityRepository
{
    
    public function ajoutPronosticDQL($resultat)
    {
      /*  return $this->getEntityManager()
            ->createQuery(
                'SELECT * FROM jeu'
            )
            ->getResult();*/
        $query=$this->getEntityManager()
            ->createQuery("SELECT v from TFTpersonneBundle:jeu v ");
          //  ->setParameter('res','%'.$resultat.'%');
    return $query->getResult();
    }
       public function findJeuDQL($id){
    $query=$this->getEntityManager()
            ->createQuery("SELECT v from TFTpersonneBundle:jeu v WHERE v.id like :ser")
            ->setParameter('ser','%'.$id.'%');
    return $query->getResult();
}
}
