tf_tpersonne:
    resource: "@TFTpersonneBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

tft_personne:
    resource : "@TFTpersonneBundle/Controller/"
    type : annotation
    prefix : /
   
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /
    defaults: { _format: html }
tf_tpersonne_graphe:
    resource: "@TFTpersonneBundle/Resources/config/routing.yml"
    prefix:   /