security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext  
    
    role_hierarchy:
        ROLE_CLIENT: ROLE_USER
        ROLE_AGENT: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
 
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: redirect.after.login
            logout: true
            anonymous: true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/arbitre/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fan/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/joueur/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/medecin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dopage/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/affichage, role: ROLE_CLIENT }